"""add_hourly_rate_to_employee_salaries

Revision ID: 0a75858bf298
Revises: b776f6d76f3f
Create Date: 2026-09-17 17:14:22.948561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a75858bf298'
down_revision: Union[str, Sequence[str], None] = 'b776f6d76f3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_salaries', sa.Column('hourly_rate', sa.Numeric(precision=14, scale=2), nullable=True))
    op.create_index(op.f('ix_project_documents_company_id'), 'project_documents', ['company_id'], unique=False)
    op.create_index(op.f('ix_project_documents_project_id'), 'project_documents', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_documents_project_id'), table_name='project_documents')
    op.drop_index(op.f('ix_project_documents_company_id'), table_name='project_documents')
    op.drop_column('employee_salaries', 'hourly_rate')
    # ### end Alembic commands ###
