"""add companies approved_by

Revision ID: 17d00ae67fda
Revises: 07da587a3d1f
Create Date: 2026-08-31 19:23:19.797989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d00ae67fda'
down_revision: Union[str, Sequence[str], None] = '07da587a3d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_companies_approved_by_users', 'companies', 'users', ['approved_by'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_companies_approved_by_users', 'companies', type_='foreignkey')
    # ### end Alembic commands ###
