"""departments

Revision ID: 2499347d1a53
Revises: e6afe6c3d30f
Create Date: 2026-09-01 18:04:59.569051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.rls import enable_rls

# revision identifiers, used by Alembic.
revision: str = '2499347d1a53'
down_revision: Union[str, Sequence[str], None] = 'e6afe6c3d30f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('head_employee_id', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_company_id'), 'departments', ['company_id'], unique=False)
    op.create_index('uq_departments_company_id_name', 'departments', ['company_id', 'name'], unique=True)
    # ### end Alembic commands ###

    # RLS policy in the same migration that creates the table (Spec 8.3).
    enable_rls("departments")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_departments_company_id_name', table_name='departments')
    op.drop_index(op.f('ix_departments_company_id'), table_name='departments')
    op.drop_table('departments')
    # ### end Alembic commands ###
