"""payroll salary structures and statutory tables

Revision ID: 2e82bdb051d1
Revises: 6f86b03e8caa
Create Date: 2026-09-03 16:46:57.615063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.rls import enable_rls

# revision identifiers, used by Alembic.
revision: str = '2e82bdb051d1'
down_revision: Union[str, Sequence[str], None] = '6f86b03e8caa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pt_slabs',
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('income_min', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('income_max', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('monthly_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('special_month', sa.SmallInteger(), nullable=True),
    sa.Column('special_month_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pt_slabs_state_effective_from', 'pt_slabs', ['state', 'effective_from'], unique=False)
    op.create_table('tax_slabs',
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('financial_year', sa.String(length=9), nullable=False),
    sa.Column('regime', sa.Enum('old', 'new', name='tax_slab_regime'), nullable=False),
    sa.Column('min_income', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('max_income', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('rate_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('cess_percent', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('surcharge_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('source_note', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tax_slabs_country_fy_regime', 'tax_slabs', ['country', 'financial_year', 'regime'], unique=False)
    op.create_table('salary_structures',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_structures_company_id'), 'salary_structures', ['company_id'], unique=False)
    op.create_index('ix_salary_structures_company_id_is_active', 'salary_structures', ['company_id', 'is_active'], unique=False)
    enable_rls("salary_structures")
    op.create_table('salary_components',
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('type', sa.Enum('earning', 'deduction', 'employer_contribution', name='salary_component_type'), nullable=False),
    sa.Column('calculation_type', sa.Enum('percentage', 'fixed', 'balance', 'statutory', name='salary_calculation_type'), nullable=False),
    sa.Column('value', sa.Numeric(precision=14, scale=3), nullable=True),
    sa.Column('percentage_of', sa.Enum('ctc', 'basic', name='salary_percentage_of'), nullable=True),
    sa.Column('is_taxable', sa.Boolean(), nullable=False),
    sa.Column('is_statutory', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['structure_id'], ['salary_structures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('structure_id', 'code', name='uq_salary_components_structure_code')
    )
    op.create_index(op.f('ix_salary_components_company_id'), 'salary_components', ['company_id'], unique=False)
    enable_rls("salary_components")
    op.create_table('statutory_configs',
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('pf_enabled', sa.Boolean(), nullable=False),
    sa.Column('pf_employee_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('pf_employer_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('pf_wage_ceiling', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pf_restrict_to_ceiling', sa.Boolean(), nullable=False),
    sa.Column('esi_enabled', sa.Boolean(), nullable=False),
    sa.Column('esi_employee_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('esi_employer_rate', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('esi_wage_ceiling', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pt_enabled', sa.Boolean(), nullable=False),
    sa.Column('pt_state', sa.String(length=50), nullable=True),
    sa.Column('lwf_enabled', sa.Boolean(), nullable=False),
    sa.Column('lwf_employee_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('lwf_months', sa.ARRAY(sa.SmallInteger()), nullable=True),
    sa.Column('tds_enabled', sa.Boolean(), nullable=False),
    sa.Column('default_tax_regime', sa.Enum('old', 'new', name='statutory_config_tax_regime'), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statutory_configs_company_id'), 'statutory_configs', ['company_id'], unique=False)
    op.create_index('uq_statutory_configs_company_id', 'statutory_configs', ['company_id'], unique=True)
    enable_rls("statutory_configs")
    op.create_table('employee_salaries',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('structure_id', sa.UUID(), nullable=False),
    sa.Column('ctc', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('revision_reason', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['structure_id'], ['salary_structures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_salaries_company_id'), 'employee_salaries', ['company_id'], unique=False)
    op.create_index('ix_employee_salaries_company_id_employee_id', 'employee_salaries', ['company_id', 'employee_id'], unique=False)
    enable_rls("employee_salaries")
    # ### end Alembic commands ###

    # pt_slabs and tax_slabs are deliberately NOT RLS-enabled (Spec 7.6):
    # government-defined, platform-managed reference data, the same
    # treatment industry_presets already gets — no company owns a state's
    # Professional Tax slab or a financial year's income-tax bracket.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employee_salaries_company_id_employee_id', table_name='employee_salaries')
    op.drop_index(op.f('ix_employee_salaries_company_id'), table_name='employee_salaries')
    op.drop_table('employee_salaries')
    op.drop_index('uq_statutory_configs_company_id', table_name='statutory_configs')
    op.drop_index(op.f('ix_statutory_configs_company_id'), table_name='statutory_configs')
    op.drop_table('statutory_configs')
    op.drop_index(op.f('ix_salary_components_company_id'), table_name='salary_components')
    op.drop_table('salary_components')
    op.drop_index('ix_salary_structures_company_id_is_active', table_name='salary_structures')
    op.drop_index(op.f('ix_salary_structures_company_id'), table_name='salary_structures')
    op.drop_table('salary_structures')
    op.drop_index('ix_tax_slabs_country_fy_regime', table_name='tax_slabs')
    op.drop_table('tax_slabs')
    op.drop_index('ix_pt_slabs_state_effective_from', table_name='pt_slabs')
    op.drop_table('pt_slabs')
    # ### end Alembic commands ###
