"""Add overtime fields to TimeEntry

Revision ID: 324644e785e6
Revises: de77160da166
Create Date: 2026-09-21 15:56:48.477800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '324644e785e6'
down_revision: Union[str, Sequence[str], None] = 'de77160da166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_pips_company_employee'), table_name='performance_pips')
    op.create_index(op.f('ix_performance_pips_company_id'), 'performance_pips', ['company_id'], unique=False)
    op.create_foreign_key(None, 'performance_pips', 'companies', ['company_id'], ['id'], ondelete='RESTRICT')
    op.add_column('time_entries', sa.Column('is_overtime', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('time_entries', sa.Column('overtime_multiplier', sa.Numeric(precision=3, scale=2), nullable=True))
    op.add_column('time_entries', sa.Column('overtime_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_entries', 'overtime_amount')
    op.drop_column('time_entries', 'overtime_multiplier')
    op.drop_column('time_entries', 'is_overtime')
    op.drop_constraint(None, 'performance_pips', type_='foreignkey')
    op.drop_index(op.f('ix_performance_pips_company_id'), table_name='performance_pips')
    op.create_index(op.f('ix_performance_pips_company_employee'), 'performance_pips', ['company_id', 'employee_id'], unique=False)
    # ### end Alembic commands ###
