"""Add company locations

Revision ID: 566a8c498f09
Revises: c2ae03ec6868
Create Date: 2026-09-21 18:57:49.427897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '566a8c498f09'
down_revision: Union[str, Sequence[str], None] = 'c2ae03ec6868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_locations',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_locations_company_id'), 'company_locations', ['company_id'], unique=False)
    op.create_index('uq_company_locations_company_id_code', 'company_locations', ['company_id', 'code'], unique=True)
    op.create_index('uq_company_locations_company_id_name', 'company_locations', ['company_id', 'name'], unique=True)
    op.add_column('employees', sa.Column('location_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'employees', 'company_locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'location_id')
    op.drop_index('uq_company_locations_company_id_name', table_name='company_locations')
    op.drop_index('uq_company_locations_company_id_code', table_name='company_locations')
    op.drop_index(op.f('ix_company_locations_company_id'), table_name='company_locations')
    op.drop_table('company_locations')
    # ### end Alembic commands ###
