"""performance_tables

Revision ID: 614e8be7cbb2
Revises: 9954d5e03577
Create Date: 2026-09-07 11:51:04.555485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614e8be7cbb2'
down_revision: Union[str, Sequence[str], None] = '9954d5e03577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('performance_cycles',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('cycle_type', sa.Enum('annual', 'half_yearly', 'quarterly', name='cycle_type'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'closed', name='cycle_status'), nullable=False),
    sa.Column('self_review_deadline', sa.Date(), nullable=True),
    sa.Column('manager_review_deadline', sa.Date(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_cycles_company_id'), 'performance_cycles', ['company_id'], unique=False)
    op.create_table('performance_goals',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weightage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_value', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'in_progress', 'completed', name='goal_status'), nullable=False),
    sa.Column('self_rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('self_comments', sa.Text(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_goals_company_id'), 'performance_goals', ['company_id'], unique=False)
    op.create_table('performance_summaries',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('final_rating', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('overall_comments', sa.Text(), nullable=True),
    sa.Column('salary_revision_recommended', sa.Boolean(), nullable=False),
    sa.Column('recommended_increment_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cycle_id'], ['performance_cycles.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'employee_id', 'cycle_id', name='uq_performance_summaries_employee_cycle')
    )
    op.create_index(op.f('ix_performance_summaries_company_id'), 'performance_summaries', ['company_id'], unique=False)
    op.create_table('performance_reviews',
    sa.Column('goal_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_role', sa.Enum('self', 'manager', 'peer', name='reviewer_role'), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['goal_id'], ['performance_goals.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'goal_id', 'reviewer_role', name='uq_performance_reviews_goal_reviewer_role')
    )
    op.create_index(op.f('ix_performance_reviews_company_id'), 'performance_reviews', ['company_id'], unique=False)
    from app.db.rls import enable_rls
    enable_rls("performance_cycles")
    enable_rls("performance_goals")
    enable_rls("performance_summaries")
    enable_rls("performance_reviews")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_performance_reviews_company_id'), table_name='performance_reviews')
    op.drop_table('performance_reviews')
    op.drop_index(op.f('ix_performance_summaries_company_id'), table_name='performance_summaries')
    op.drop_table('performance_summaries')
    op.drop_index(op.f('ix_performance_goals_company_id'), table_name='performance_goals')
    op.drop_table('performance_goals')
    op.drop_index(op.f('ix_performance_cycles_company_id'), table_name='performance_cycles')
    op.drop_table('performance_cycles')
    # ### end Alembic commands ###
