"""add_geofence_columns_to_company_locations

Revision ID: ab4df060ab27
Revises: 566a8c498f09
Create Date: 2026-09-21 19:15:58.512097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4df060ab27'
down_revision: Union[str, Sequence[str], None] = '566a8c498f09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_locations', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('company_locations', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('company_locations', sa.Column('geofence_radius_meters', sa.Integer(), nullable=False))
    op.add_column('company_locations', sa.Column('is_remote_exempt', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_locations', 'is_remote_exempt')
    op.drop_column('company_locations', 'geofence_radius_meters')
    op.drop_column('company_locations', 'longitude')
    op.drop_column('company_locations', 'latitude')
    # ### end Alembic commands ###
