"""employees

Revision ID: b0a30daaecff
Revises: 2499347d1a53
Create Date: 2026-09-01 18:44:21.598063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.rls import enable_rls

# revision identifiers, used by Alembic.
revision: str = 'b0a30daaecff'
down_revision: Union[str, Sequence[str], None] = '2499347d1a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('employee_code', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('personal_email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('position', sa.String(length=150), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('reporting_manager_id', sa.UUID(), nullable=True),
    sa.Column('employment_type', sa.Enum('full_time', 'part_time', 'contract', 'intern', name='employment_type'), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=False),
    sa.Column('probation_end_date', sa.Date(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('invitation_status', sa.Enum('not_sent', 'sent', 'activated', 'expired', name='invitation_status'), nullable=False),
    sa.Column('activation_token_hash', sa.Text(), nullable=True),
    sa.Column('activation_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resignation_status', sa.Enum('none', 'submitted', 'approved', 'rejected', name='resignation_status'), nullable=False),
    sa.Column('resignation_date', sa.Date(), nullable=True),
    sa.Column('last_working_date', sa.Date(), nullable=True),
    sa.Column('notice_waived', sa.Boolean(), nullable=False),
    sa.Column('notice_recovery_days', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('reporting_manager_id <> id', name='ck_employees_manager_not_self'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_employees_company_id'), 'employees', ['company_id'], unique=False)
    op.create_index('ix_employees_company_id_department_id', 'employees', ['company_id', 'department_id'], unique=False)
    op.create_index('ix_employees_company_id_is_active', 'employees', ['company_id', 'is_active'], unique=False)
    op.create_index('ix_employees_reporting_manager_id', 'employees', ['reporting_manager_id'], unique=False)
    op.create_index('uq_employees_company_id_email', 'employees', ['company_id', 'email'], unique=True)
    op.create_index('uq_employees_company_id_employee_code', 'employees', ['company_id', 'employee_code'], unique=True)
    # ### end Alembic commands ###

    # RLS policy in the same migration that creates the table (Spec 8.3).
    enable_rls("employees")

    # departments.head_employee_id -> employees.id is added in a separate,
    # follow-up migration (see the next revision) rather than here — same
    # reasoning as the companies.approved_by / users cycle (7.2): this keeps
    # each migration scoped to the table it creates.


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_employees_company_id_employee_code', table_name='employees')
    op.drop_index('uq_employees_company_id_email', table_name='employees')
    op.drop_index('ix_employees_reporting_manager_id', table_name='employees')
    op.drop_index('ix_employees_company_id_is_active', table_name='employees')
    op.drop_index('ix_employees_company_id_department_id', table_name='employees')
    op.drop_index(op.f('ix_employees_company_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
