"""attendance shifts employee_shifts

Revision ID: b4578ccda3b8
Revises: f1a2b3c4d5e6
Create Date: 2026-09-01 23:40:24.024890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db.rls import enable_rls

# revision identifiers, used by Alembic.
revision: str = 'b4578ccda3b8'
down_revision: Union[str, Sequence[str], None] = 'f1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_minutes', sa.Integer(), nullable=False),
    sa.Column('night_allowance', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_company_id'), 'shifts', ['company_id'], unique=False)
    op.create_table('attendance',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('present', 'absent', 'half_day', 'wfh', 'on_leave', 'holiday', 'weekend', name='attendance_status'), nullable=False),
    sa.Column('hours_worked', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source', sa.Enum('web', 'mobile', 'system', 'import', name='attendance_source'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'date', name='uq_attendance_employee_id_date')
    )
    op.create_index(op.f('ix_attendance_company_id'), 'attendance', ['company_id'], unique=False)
    op.create_index('ix_attendance_company_id_date', 'attendance', ['company_id', 'date'], unique=False)
    op.create_index('ix_attendance_employee_id_date', 'attendance', ['employee_id', 'date'], unique=False)
    op.create_table('employee_shifts',
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_shifts_company_id'), 'employee_shifts', ['company_id'], unique=False)
    op.create_index('ix_employee_shifts_employee_id', 'employee_shifts', ['employee_id'], unique=False)
    # ### end Alembic commands ###

    # RLS policy in the same migration that creates each table (Spec 8.3).
    enable_rls("shifts")
    enable_rls("attendance")
    enable_rls("employee_shifts")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employee_shifts_employee_id', table_name='employee_shifts')
    op.drop_index(op.f('ix_employee_shifts_company_id'), table_name='employee_shifts')
    op.drop_table('employee_shifts')
    op.drop_index('ix_attendance_employee_id_date', table_name='attendance')
    op.drop_index('ix_attendance_company_id_date', table_name='attendance')
    op.drop_index(op.f('ix_attendance_company_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_shifts_company_id'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
