"""Add mispunch and regularization

Revision ID: c2ae03ec6868
Revises: 324644e785e6
Create Date: 2026-09-21 15:59:09.626342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2ae03ec6868'
down_revision: Union[str, Sequence[str], None] = '324644e785e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE attendance_status ADD VALUE IF NOT EXISTS 'mispunch'")
    op.execute("ALTER TYPE attendance_status ADD VALUE IF NOT EXISTS 'pending_regularization'")
    op.create_table('attendance_regularizations',
    sa.Column('attendance_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('manager_id', sa.UUID(), nullable=True),
    sa.Column('requested_check_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_check_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='regularization_status'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_regularizations_company_attendance', 'attendance_regularizations', ['company_id', 'attendance_id'], unique=False)
    op.create_index(op.f('ix_attendance_regularizations_company_id'), 'attendance_regularizations', ['company_id'], unique=False)
    op.create_index('ix_attendance_regularizations_company_manager', 'attendance_regularizations', ['company_id', 'manager_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_attendance_regularizations_company_manager', table_name='attendance_regularizations')
    op.drop_index(op.f('ix_attendance_regularizations_company_id'), table_name='attendance_regularizations')
    op.drop_index('ix_attendance_regularizations_company_attendance', table_name='attendance_regularizations')
    op.drop_table('attendance_regularizations')
    # ### end Alembic commands ###
