"""payroll_runs_and_payroll_items

Revision ID: cfb371971f62
Revises: 2e82bdb051d1
Create Date: 2026-09-03 18:32:14.229534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.rls import enable_rls

# revision identifiers, used by Alembic.
revision: str = 'cfb371971f62'
down_revision: Union[str, Sequence[str], None] = '2e82bdb051d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll_runs',
    sa.Column('month', sa.SmallInteger(), nullable=False),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'processing', 'pending_approval', 'approved', 'paid', 'failed', name='payroll_run_status'), nullable=False),
    sa.Column('run_type', sa.Enum('regular', 'off_cycle', name='payroll_run_type'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('total_employees', sa.Integer(), nullable=True),
    sa.Column('total_gross', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_deductions', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_net', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_employer_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('run_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'idempotency_key', name='uq_payroll_runs_company_idempotency_key')
    )
    op.create_index(op.f('ix_payroll_runs_company_id'), 'payroll_runs', ['company_id'], unique=False)
    op.create_index('uq_payroll_runs_company_month_year_regular', 'payroll_runs', ['company_id', 'month', 'year'], unique=True, postgresql_where=sa.text("run_type = 'regular'"))
    enable_rls("payroll_runs")
    op.create_table('payroll_items',
    sa.Column('payroll_run_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.UUID(), nullable=False),
    sa.Column('ctc_snapshot', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('employer_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('earnings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('deductions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('employer_contributions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('working_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('present_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('absent_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('half_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('paid_leave_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('lop_days', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('reimbursement_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payroll_run_id', 'employee_id', name='uq_payroll_items_run_employee')
    )
    op.create_index(op.f('ix_payroll_items_company_id'), 'payroll_items', ['company_id'], unique=False)
    enable_rls("payroll_items")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_items_company_id'), table_name='payroll_items')
    op.drop_table('payroll_items')
    op.drop_index('uq_payroll_runs_company_month_year_regular', table_name='payroll_runs', postgresql_where=sa.text("run_type = 'regular'"))
    op.drop_index(op.f('ix_payroll_runs_company_id'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    # ### end Alembic commands ###
