"""company_settings

Revision ID: d2e48d131137
Revises: 17d00ae67fda
Create Date: 2026-09-01 17:33:30.236218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.db.rls import enable_rls

# revision identifiers, used by Alembic.
revision: str = 'd2e48d131137'
down_revision: Union[str, Sequence[str], None] = '17d00ae67fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_settings',
    sa.Column('weekend_days', postgresql.ARRAY(sa.SmallInteger()), nullable=False),
    sa.Column('half_day_hours_threshold', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('full_day_hours', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('leave_year_type', sa.Enum('calendar', 'financial', name='leave_year_type'), nullable=False),
    sa.Column('leave_year_start_month', sa.SmallInteger(), nullable=False),
    sa.Column('payroll_working_days_basis', sa.Enum('calendar_days', 'working_days', 'fixed_30', name='payroll_working_days_basis'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_settings_company_id'), 'company_settings', ['company_id'], unique=False)
    op.create_index('uq_company_settings_company_id', 'company_settings', ['company_id'], unique=True)
    # ### end Alembic commands ###

    # RLS policy in the same migration that creates the table (Spec 8.3) —
    # autogenerate never emits this; it must be added by hand every time.
    enable_rls("company_settings")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_company_settings_company_id', table_name='company_settings')
    op.drop_index(op.f('ix_company_settings_company_id'), table_name='company_settings')
    op.drop_table('company_settings')
    # ### end Alembic commands ###
