"""industry_presets

Revision ID: e6afe6c3d30f
Revises: d2e48d131137
Create Date: 2026-09-01 17:55:20.338493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6afe6c3d30f'
down_revision: Union[str, Sequence[str], None] = 'd2e48d131137'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('industry_presets',
    sa.Column('industry_name', sa.String(length=100), nullable=False),
    sa.Column('departments_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('leave_types_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_industry_presets_industry_name', 'industry_presets', ['industry_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_industry_presets_industry_name', table_name='industry_presets')
    op.drop_table('industry_presets')
    # ### end Alembic commands ###
